# Brownie configuration file
# https://eth-brownie.readthedocs.io/en/stable/config.html
compiler:
    evm_version: constantinople
    solc:
        version: null
        optimizer:
            enabled: true
            runs: 1000000
            details:
                deduplicate: true
                constantOptimizer: true
                cse: true
                yul: true
        remappings: "@0x=contracts/exchange"